-- Run this in the Supabase SQL Editor before starting the dashboard.
create table if not exists public.sensor_data (
    id bigint generated by default as identity primary key,
    temperature double precision not null,
    humidity double precision not null,
    mq_value double precision not null,
    moisture double precision not null,
    created_at timestamptz not null default now()
);

create index if not exists sensor_data_created_at_desc_idx
    on public.sensor_data (created_at desc);

alter table public.sensor_data enable row level security;

-- Requests are made by Next.js Route Handlers with a server-side key; never put that key in browser code.